-- ============================================================
-- MW Transport Service — Phase 2 schema (orders + customers)
-- Multi-tenant with Row Level Security. Run in the Supabase SQL editor.
-- ------------------------------------------------------------
-- Isolation model: every business row carries a tenant_id. A user
-- belongs to one or more tenants via `memberships`. RLS policies let
-- a user touch a row only when they have a membership for its tenant.
-- ============================================================

-- ---------- Extensions ----------
create extension if not exists "pgcrypto"; -- gen_random_uuid()

-- ---------- Tenants ----------
create table if not exists public.tenants (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  brand       text default 'Grün',
  label       text,
  created_at  timestamptz not null default now()
);

-- ---------- Memberships (auth.users -> tenant) ----------
create table if not exists public.memberships (
  user_id    uuid not null references auth.users(id) on delete cascade,
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  role       text not null default 'dispatcher',
  primary key (user_id, tenant_id)
);

-- Helper: tenants the current user may access.
create or replace function public.current_tenant_ids()
returns setof uuid
language sql
stable
security definer
set search_path = public
as $$
  select tenant_id from public.memberships where user_id = auth.uid();
$$;

-- ---------- Customers ----------
create table if not exists public.customers (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  display_id    text,
  name          text not null,
  short_name    text,
  email         text,
  phone         text,
  land          text default 'Deutschland',
  city          text,
  street        text,
  plz           text,
  contacts      jsonb not null default '[]'::jsonb,
  dispo_ausland text,
  durchfuehrung text,
  rechnung      text,
  order_count   integer not null default 0,
  open_orders   integer not null default 0,
  created_at    timestamptz not null default now()
);
create index if not exists customers_tenant_idx on public.customers (tenant_id);

-- ---------- Orders ----------
create table if not exists public.orders (
  id             uuid primary key default gen_random_uuid(),
  tenant_id      uuid not null references public.tenants(id) on delete cascade,
  order_no       bigint generated by default as identity,
  mv_nr          text,
  plate          text,
  model          text,
  vin            text,
  customer_id    uuid references public.customers(id) on delete set null,
  auftraggeber   text,
  from_city      text,
  from_plz       text,
  from_street    text,
  to_city        text,
  to_plz         text,
  to_street      text,
  pickup_date    date,
  pickup_window  text,
  delivery_date  date,
  status         text not null default 'nicht_zugewiesen',
  driver_id      text,
  driver_name    text,
  driver_phone   text,
  driver_city    text,
  job_type       text,
  bundesland     text,
  price          numeric not null default 0,
  price_selbst   numeric not null default 0,
  km             integer not null default 0,
  refuel         boolean not null default false,
  arbeitsnachweis text,
  created_at     timestamptz not null default now()
);
create index if not exists orders_tenant_idx on public.orders (tenant_id);
create index if not exists orders_status_idx on public.orders (tenant_id, status);

-- ============================================================
-- Row Level Security
-- ============================================================
alter table public.tenants     enable row level security;
alter table public.memberships enable row level security;
alter table public.customers   enable row level security;
alter table public.orders      enable row level security;

-- A user can read tenants / memberships they belong to.
create policy "tenants_select_own" on public.tenants
  for select using ( id in (select public.current_tenant_ids()) );

create policy "memberships_select_own" on public.memberships
  for select using ( user_id = auth.uid() );

-- Customers: full CRUD only within the user's tenant(s).
create policy "customers_select" on public.customers
  for select using ( tenant_id in (select public.current_tenant_ids()) );
create policy "customers_insert" on public.customers
  for insert with check ( tenant_id in (select public.current_tenant_ids()) );
create policy "customers_update" on public.customers
  for update using ( tenant_id in (select public.current_tenant_ids()) )
              with check ( tenant_id in (select public.current_tenant_ids()) );
create policy "customers_delete" on public.customers
  for delete using ( tenant_id in (select public.current_tenant_ids()) );

-- Orders: full CRUD only within the user's tenant(s).
create policy "orders_select" on public.orders
  for select using ( tenant_id in (select public.current_tenant_ids()) );
create policy "orders_insert" on public.orders
  for insert with check ( tenant_id in (select public.current_tenant_ids()) );
create policy "orders_update" on public.orders
  for update using ( tenant_id in (select public.current_tenant_ids()) )
              with check ( tenant_id in (select public.current_tenant_ids()) );
create policy "orders_delete" on public.orders
  for delete using ( tenant_id in (select public.current_tenant_ids()) );
